# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Hugo Recital"
license = "MIT"
licenselink = "https://github.com/tily/hugo-recital/blob/master/LICENSE.md"
description = ""
homepage = "https://github.com/tily/hugo-recital"
tags = ["", ""]
features = ["", ""]
min_version = 0.17

[author]
  name = ""
  homepage = ""

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
